#apiVersion: v1
#kind: Namespace
#metadata:
#  name: zisefeizhu-dev
#  labels:
#    test: zisefeizhu
---
apiVersion: workloads.zise.feizhu/v1alpha1
kind: Workload
metadata:
  name: dev
  namespace: zisefeizhu-dev
  labels:
    test: zisefeizhu
    test1: zisefeizhu1
spec:
# # type: deployment/statefulSet/daemonSet/job/cronJob 
  type: job
  selector:
    matchLabels:
      test: zisefeizhu
      test1: zisefeizhu1
  replicas: 1
  jobBackoffLimit: 2
  serviceType: NodePort 
  servicePorts:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  enableService: false
  template:
    spec:
      containers:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
