#apiVersion: v1
#kind: Namespace
#metadata:
#  name: zisefeizhu-dev
#  labels:
#    test: zisefeizhu
---
apiVersion: workloads.zise.feizhu/v1alpha1
kind: Workload
metadata:
  name: dev
  namespace: zisefeizhu-dev
  labels:
    test: zisefeizhu
    test1: zisefeizhu1
spec:
# # type: deployment/statefulSet/daemonSet/job/cronJob 
  type: cronJob
  selector:
    matchLabels:
      test: zisefeizhu
      test1: zisefeizhu1
  replicas: 1
  serviceType: NodePort 
  servicePorts:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  enableService: false
  schedule: "* * * * *"  
  template:
    metadata:
      labels:
        test: zisefeizhu
        test1: zisefeizhu1
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster
      restartPolicy: OnFailure
      
